-- plays sounds when disassembling items/using repair items
-- oleh5230, 18.11.25
-- Last edit: 01.09.26

debug = false

function itms_manager.print_dbg(txt, ...)
	if debug then
		printf("[itms_manager_snd_on_use] " .. txt, ...)
	end
end

snd_on_use = {
	["cap"]					= {"interface\\items_use\\cap_1"},

	["glue"]				= {"interface\\items_use\\glue_1"},
	["scissors"]			= {"interface\\items_use\\scissors_1"},
	["tape"]				= {"interface\\items_use\\tape_1"},
	["parts_fabric"]		= {"interface\\items_use\\parts_fabric_1"},

	["oil"]					= {"interface\\items_use\\oil_1"},
	["spray"]				= {"interface\\items_use\\spray_1"},
	["parts_metal"]			= {"interface\\items_use\\parts_metal_1"},

	["clean"]				= {"interface\\items_use\\clean_1"},
	["file"]				= {"interface\\items_use\\file_1"},
	["sharp"]				= {"interface\\items_use\\sharp_1"},
}

local time_snd_prev = 0
function itms_manager.play_use_sound(item, vol)
	if (not item) then
		printe("!ERROR itms_manager_snd_on_take | play_use_sound | no object recieved!")
		return
	end

	local snd_type = SYS_GetParam(0,item:section(),"snd_on_use")
	if not (snd_type and snd_type ~= "") then
		return
	end

	local snd = snd_on_use[snd_type]
	if (not snd) then
		return
	end

	local snd_obj
	if (#snd == 1) then
		snd_obj = sound_object(snd[1])
	else
		snd_obj = sound_object(snd[1] .. tostring(math.random(snd[2],snd[3])))
	end

	local time_g = time_global()
	if snd_obj and (time_g > time_snd_prev + 200) then
		snd_obj:play(db.actor,0,sound_object.s2d)
		snd_obj.volume = vol or 1
	end
	time_snd_prev = time_g
end
