-- more rain sound samples
-- volume interpolation
-- MCM settings
-- Spatial Audio Rework patch
-- oleh5230, 17.09.26

local low = "rain_weak"
local med = "rain_medium"
local big = "rain_strong"
local hlm_low = "rain_helm_weak"
local hlm_med = "rain_helm_medium"
local hlm_big = "rain_helm_strong"
local int = "rain_indoors"

local vol_low = 0
local vol_med = 0
local vol_big = 0
local vol_hlm_low = 0
local vol_hlm_med = 0
local vol_hlm_big = 0
local vol_int = 0

local step = 0.01

local volume_outdoor_rain = 1
local volume_indoor_rain = 1
local volume_helmet_rain = 1
local volume_master_rain = 1

local clamp = clamp
local opt = {
	ambient_volume = 1,
	effects_wind_enabled = true,
	effects_rain_enabled = true,
}
update_rain_helm_sound = sound_ambient.update_rain_helm_sound
function sound_ambient.update_rain_helm_sound(rain_factor, rain_volume, inside, bLevelUnderground)

	if not bLevelUnderground and rain_factor > 0 and opt.effects_rain_enabled then
		--if sar_snd_replacer and sar_snd_replacer.isIndoor(db.actor) >= 1 or level.rain_hemi() < 0.25 then
		if level.rain_hemi() < 0.05 then
			vol_low = clamp(vol_low - step,0,1)
			vol_med	= clamp(vol_med - step,0,1)
			vol_big	= clamp(vol_big - step,0,1)

			--vol_hlm_low = 0 --clamp(vol_low - step,0,1)
			vol_hlm_med	= 0 --clamp(vol_med - step,0,1)
			vol_hlm_big	= 0 --clamp(vol_big - step,0,1)

			if rain_factor > 0.4 then
				vol_int = clamp(vol_int + step,0,1)
			end

		else
			if rain_factor > 0.8 then
				vol_low = clamp(vol_low - step,0,1)
				vol_med	= clamp(vol_med - step,0,1)
				vol_big	= clamp(vol_big + step,0,1)

				-- vol_hlm_low = clamp(vol_hlm_low - step,0,1)
				vol_hlm_med	= clamp(vol_hlm_med - step,0,1)
				vol_hlm_big	= actor_effects.is_mask_on() and 1 or clamp(vol_hlm_big - step,0,1)

			elseif rain_factor > 0.4 then
				vol_low = clamp(vol_low - step,0,1)
				vol_med	= clamp(vol_med + step,0,1)
				vol_big	= clamp(vol_big - step,0,1)

				-- vol_hlm_low = clamp(vol_hlm_low - step,0,1)
				vol_hlm_med	= actor_effects.is_mask_on() and 1 or clamp(vol_hlm_med - step,0,1)
				vol_hlm_big	= 0 --clamp(vol_hlm_big - step,0,1)

			else
				vol_low = clamp(vol_low + step,0,1)
				vol_med	= clamp(vol_med - step,0,1)
				vol_big	= clamp(vol_big - step,0,1)

				-- vol_hlm_low = actor_effects.is_mask_on() and clamp(vol_hlm_low + step,0,1) or clamp(vol_hlm_low - step,0,1)
				vol_hlm_med	= 0 --clamp(vol_hlm_med - step,0,1)
				vol_hlm_big	= 0 --clamp(vol_hlm_big - step,0,1)
			end

			vol_int = clamp(vol_int - step,0,1)
		end

	else
		vol_low = clamp(vol_low - step,0,1)
		vol_med	= clamp(vol_med - step,0,1)
		vol_big	= clamp(vol_big - step,0,1)

		-- vol_hlm_low = clamp(vol_low - step,0,1)
		vol_hlm_med	= clamp(vol_med - step,0,1)
		vol_hlm_big	= clamp(vol_big - step,0,1)

		vol_int = clamp(vol_int - step,0,1)
	end

	xr_sound.set_volume_sound_looped(AC_ID, low, vol_low * rain_volume * volume_outdoor_rain)
	xr_sound.set_volume_sound_looped(AC_ID, med, vol_med * rain_volume * volume_outdoor_rain)
	xr_sound.set_volume_sound_looped(AC_ID, big, vol_big * rain_volume * volume_outdoor_rain)

	-- xr_sound.set_volume_sound_looped(AC_ID, hlm_low, vol_hlm_low * rain_volume)
	xr_sound.set_volume_sound_looped(AC_ID, hlm_med, vol_hlm_med * rain_volume * volume_helmet_rain)
	xr_sound.set_volume_sound_looped(AC_ID, hlm_big, vol_hlm_big * rain_volume * volume_helmet_rain)

	xr_sound.set_volume_sound_looped(AC_ID, int, vol_int * volume_indoor_rain)

	--printf("Dynamic rain sounds - rain_factor: %s, rain_volume: %s, low: %s, med: %s, big: %s, int: %s", rain_factor, rain_volume, vol_low, vol_med, vol_big, vol_int)
end

local function update_settings()
	opt.effects_rain_enabled = ui_options.get("sound/environment/helmet_rain_sound")
	opt.ambient_volume = ui_options.get("sound/environment/ambient_volume")

	if ui_mcm and oleh_sounds_mcm and oleh_sounds_mcm.on_mcm_load then
		volume_master_rain 		= ui_mcm.get("oleh_sounds/environment/volume_rain_master") or 1
		volume_outdoor_rain 	= (ui_mcm.get("oleh_sounds/environment/volume_rain_outdoor") * volume_master_rain) or 1
		volume_indoor_rain 		= (ui_mcm.get("oleh_sounds/environment/volume_rain_indoor") * volume_master_rain) or 1
		volume_helmet_rain 		= (ui_mcm.get("oleh_sounds/environment/volume_rain_helmet") * volume_master_rain) or 1
	end
end

local function actor_on_first_update()
	xr_sound.play_sound_looped(AC_ID, low)
	xr_sound.play_sound_looped(AC_ID, med)
	xr_sound.play_sound_looped(AC_ID, big)

	-- xr_sound.play_sound_looped(AC_ID, hlm_low)
	xr_sound.play_sound_looped(AC_ID, hlm_med)
	xr_sound.play_sound_looped(AC_ID, hlm_big)

	xr_sound.play_sound_looped(AC_ID, int)

	xr_sound.set_volume_sound_looped(AC_ID, low, 0)
	xr_sound.set_volume_sound_looped(AC_ID, med, 0)
	xr_sound.set_volume_sound_looped(AC_ID, big, 0)

	-- xr_sound.set_volume_sound_looped(AC_ID, hlm_low, 0)
	xr_sound.set_volume_sound_looped(AC_ID, hlm_med, 0)
	xr_sound.set_volume_sound_looped(AC_ID, hlm_big, 0)

	xr_sound.set_volume_sound_looped(AC_ID, int, 0)

	update_settings()
end

function GUI_on_hide(name)
	if name == "WeatherEditor" then
		sound_ambient.update_rain_helm_sound(0, 0, false, false)
	end
end

function on_game_start()
	--RegisterScriptCallback("GUI_on_hide",GUI_on_hide)
	RegisterScriptCallback("actor_on_first_update",actor_on_first_update)
	RegisterScriptCallback("on_option_change",update_settings)
end
