if not (z_auto_looter and z_auto_looter.handle_loot) then return end
printf("loading monkeypatch: z_auto_looter_sounds_oleh")

handle_loot = z_auto_looter.handle_loot
function z_auto_looter.handle_loot(...)
	if itms_manager.timeout_snd_on_take then
		itms_manager.timeout_snd_on_take()
		local snd_obj = sound_object("interface\\inv_move_all_" .. math.random(4))
		snd_obj:play(db.actor,0,sound_object.s2d)
	end
	handle_loot(...)
end