zzz_rax_sortingplus_mcm.snd_open = sound_object([[$no_sound]])

sounds = {
    sound_object([[interface\inv_open_loot_1]]),
    sound_object([[interface\inv_open_loot_2]]),
    sound_object([[interface\inv_open_loot_3]]),
    sound_object([[interface\inv_open_loot_4]]),
}

local time_snd_prev = 0
LMode_Init = ui_inventory.UIInventory.LMode_Init
ui_inventory.UIInventory.LMode_Init = function(self, obj)
    local tg = time_global()
    if tg > time_snd_prev + 200 then
        local snd_open = sounds[math.random(#sounds)]
        self:PlaySND(snd_open)

        time_snd_prev = tg
    end

    LMode_Init(self, obj)
end